// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN4fHOzToSeLa1k38L89b7OJ7ARSp9DhM',
    appId: '1:657400578546:web:0f7b1f7cd283490f94ab6b',
    messagingSenderId: '657400578546',
    projectId: 'backendfirst-7cecd',
    authDomain: 'backendfirst-7cecd.firebaseapp.com',
    storageBucket: 'backendfirst-7cecd.firebasestorage.app',
    measurementId: 'G-RXHGQWWSG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8S185YHNC7CyE_hkFmr9nfpWcW61d3I',
    appId: '1:657400578546:android:9a711e01c45b867e94ab6b',
    messagingSenderId: '657400578546',
    projectId: 'backendfirst-7cecd',
    storageBucket: 'backendfirst-7cecd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pDgmPYRhVZKSXdbG85MDNYbkRvIj0ww',
    appId: '1:657400578546:ios:fbdfd32d5d63833094ab6b',
    messagingSenderId: '657400578546',
    projectId: 'backendfirst-7cecd',
    storageBucket: 'backendfirst-7cecd.firebasestorage.app',
    iosBundleId: 'com.example.firstBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2pDgmPYRhVZKSXdbG85MDNYbkRvIj0ww',
    appId: '1:657400578546:ios:fbdfd32d5d63833094ab6b',
    messagingSenderId: '657400578546',
    projectId: 'backendfirst-7cecd',
    storageBucket: 'backendfirst-7cecd.firebasestorage.app',
    iosBundleId: 'com.example.firstBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN4fHOzToSeLa1k38L89b7OJ7ARSp9DhM',
    appId: '1:657400578546:web:093febb6e93c005994ab6b',
    messagingSenderId: '657400578546',
    projectId: 'backendfirst-7cecd',
    authDomain: 'backendfirst-7cecd.firebaseapp.com',
    storageBucket: 'backendfirst-7cecd.firebasestorage.app',
    measurementId: 'G-4DR1J8Y470',
  );
}
